.\" Copyright © 2014 Anthony J. Bentley <anthhony@cathet.us>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd November 20, 2014
.Dt SCROT 1
.Os
.Sh NAME
.Nm scrot
.Nd capture a screenshot
.Sh SYNOPSIS
.Nm scrot
.Op Fl bchmsv
.Op Fl d Ar n
.Op Fl e Ar command
.Op Fl q Ar level
.Op Fl t Ar n
.Op Ar file
.Sh DESCRIPTION
.Nm scrot
takes a screenshot and saves it to
.Ar file
(if specified) or to a timestamped filename.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl b , Fl -border
.It Fl c , Fl -count
.It Fl d Ar n , Fl -delay Ar n
.It Fl e Ar command , Fl -exec Ar command
.It Fl h , Fl -help
.It Fl m , Fl -multidisp
.It Fl q Ar level , Fl -quality Ar level
.It Fl s , Fl -select
.It Fl t Ar n , Fl -thumb Ar n
.It Fl v , Fl -version
.El
.Sh AUTHORS
.Nm
was originally written by
.An Tom Gilbert Aq Mt gilbertt@linuxbrit.co.uk .
